# Base Kubernetes manifests for CRMS CI G UK

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - minio.yaml
  - backend.yaml
  - frontend.yaml
  - nginx.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: crms
  app.kubernetes.io/managed-by: kustomize
