apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crms

resources:
  - ../../base

images:
  - name: ghcr.io/crms-ci-g-uk/backend
    newTag: staging
  - name: ghcr.io/crms-ci-g-uk/frontend
    newTag: staging

configMapGenerator:
  - name: crms-config
    behavior: replace
    literals:
      - SPRING_PROFILES_ACTIVE=staging
      - HMRC_API_MODE=sandbox

replicas:
  - name: crms-backend
    count: 2
  - name: crms-frontend
    count: 2
