apiVersion: v1
kind: Namespace
metadata:
  name: crms
  labels:
    app.kubernetes.io/name: crms
    app.kubernetes.io/managed-by: kubectl
---
apiVersion: v1
kind: Namespace
metadata:
  name: crms-infra
  labels:
    app.kubernetes.io/name: crms-infra
