apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crms.fullname" . }}-config
  namespace: {{ include "crms.namespace" . }}
  labels:
    {{- include "crms.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.backend.env.SPRING_PROFILES_ACTIVE | quote }}
  TZ: {{ .Values.backend.env.TZ | quote }}
  JAVA_OPTS: "-Xms512m -Xmx2g -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError"
  SERVER_PORT: "8080"
