{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crms.fullname" . }}-secrets
  namespace: {{ include "crms.namespace" . }}
  labels:
    {{- include "crms.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ required "postgresql.auth.password is required" .Values.postgresql.auth.password }}
  MINIO_ACCESS_KEY: {{ required "minio.auth.rootUser is required" .Values.minio.auth.rootUser }}
  MINIO_SECRET_KEY: {{ required "minio.auth.rootPassword is required" .Values.minio.auth.rootPassword }}
  APP_SECRET_KEY: {{ required "secrets.appSecretKey is required" .Values.secrets.appSecretKey }}
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret }}
{{- end }}
